# Generated by Django 5.2.17 on 2026-08-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='secondary_color',
            field=models.CharField(default='#150089', help_text='Color de apoyo. Sobreescribe la rampa `--ds-info-*`.', max_length=7),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='primary_color',
            field=models.CharField(default='#349AFE', help_text='Color de marca. Sobreescribe la rampa `--ds-brand-*`.', max_length=7),
        ),
    ]
