# Generated by Django 5.2.17 on 2026-08-12 15:54

import django.core.validators
import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_secondary_color_alter_tenant_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.FileField(blank=True, help_text='Reemplaza la inicial en la cabecera.', null=True, upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'webp'], message='El logotipo debe ser PNG, JPG, SVG o WEBP.'), tenants.models.validar_peso_logo]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subtitle',
            field=models.CharField(blank=True, default='Vinculación con la Sociedad', help_text='La línea bajo el nombre en la cabecera.', max_length=120),
        ),
    ]
