# Generated by Django 5.2.17 on 2026-08-10 15:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('code', models.CharField(db_index=True, help_text='Identificador único en MAYÚSCULAS, sin espacios.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_catalog_code', message='El código debe empezar con letra mayúscula y sólo puede contener mayúsculas, dígitos, guion bajo (_) y guion (-).', regex='^[A-Z][A-Z0-9_-]*$')])),
                ('name', models.CharField(db_index=True, help_text='Etiqueta legible mostrada al usuario.', max_length=200)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Posición en el proceso. Define el orden en pantalla.')),
                ('color', models.CharField(default='blue', help_text='Color de la tarjeta de métrica: blue, darkblue, orange, red, green.', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Etapa de Emprendimiento',
                'verbose_name_plural': 'Etapas de Emprendimiento',
                'db_table': 'ent_stage',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('code', models.CharField(blank=True, db_index=True, default='', help_text='Identificador legible del proyecto.', max_length=30)),
                ('title', models.TextField(help_text='Título del proyecto. En el formulario es un textarea: admite el contexto o la motivación institucional.')),
                ('progress', models.PositiveSmallIntegerField(default=0, help_text='Avance en porcentaje (0-100). Lo muestra la columna "Avance".')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('stage', models.ForeignKey(blank=True, help_text='Etapa actual. Nula mientras no arranque el proceso.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='entrepreneurship.stage')),
            ],
            options={
                'verbose_name': 'Proyecto de Emprendimiento',
                'verbose_name_plural': 'Proyectos de Emprendimiento',
                'db_table': 'ent_project',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('code', ''), _negated=True)), fields=('code',), name='ent_project_unique_code_alive')],
            },
        ),
    ]
