# Generated by Django 5.2.17 on 2026-08-10 16:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='progress',
        ),
        migrations.CreateModel(
            name='StageActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('code', models.CharField(db_index=True, help_text='Identificador único en MAYÚSCULAS, sin espacios.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_catalog_code', message='El código debe empezar con letra mayúscula y sólo puede contener mayúsculas, dígitos, guion bajo (_) y guion (-).', regex='^[A-Z][A-Z0-9_-]*$')])),
                ('name', models.CharField(db_index=True, help_text='Etiqueta legible mostrada al usuario.', max_length=200)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_optional', models.BooleanField(db_index=True, default=False, help_text='Si es verdadero, la actividad se elige por proyecto y solo cuenta para el avance cuando fue elegida. Si es falso, aplica siempre.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='entrepreneurship.stage')),
            ],
            options={
                'verbose_name': 'Actividad de Etapa',
                'verbose_name_plural': 'Actividades de Etapa',
                'db_table': 'ent_stage_activity',
                'ordering': ['stage', 'order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(db_index=True, default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='entrepreneurship.project')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_activities', to='entrepreneurship.stageactivity')),
            ],
            options={
                'verbose_name': 'Actividad del Proyecto',
                'verbose_name_plural': 'Actividades del Proyecto',
                'db_table': 'ent_project_activity',
                'ordering': ['activity__stage__order', 'activity__order'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'activity'), name='ent_project_activity_unique_alive')],
            },
        ),
    ]
