# Generated by Django 5.2.17 on 2026-08-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurship', '0002_remove_project_progress_stageactivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageactivity',
            name='is_derived',
            field=models.BooleanField(db_index=True, default=False, help_text='Si es verdadero, la actividad NO se confirma a mano: se marca sola cuando el proyecto ya eligió actividades en todas las etapas que admiten elección. Es el caso de "Formulación de la Idea", donde justamente se hacen esas elecciones.'),
        ),
    ]
