# Generated by Django 5.2.17 on 2026-08-12 15:06

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurship', '0004_catalog_codes_to_english'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('project_code_prefix', models.CharField(default='PE', help_text='Letras con las que empieza el código. Ejemplo: PE → PE-2026-001', max_length=10, validators=[django.core.validators.RegexValidator(message='El prefijo debe empezar con letra mayúscula y solo admite mayúsculas, dígitos y guion.', regex='^[A-Z][A-Z0-9-]*$')])),
                ('project_code_include_year', models.BooleanField(default=True, help_text='Si el código lleva el año. Con año: PE-2026-001. Sin año: PE-001.')),
                ('project_code_digits', models.PositiveSmallIntegerField(default=3, help_text='Cuántos dígitos tiene el correlativo. 3 → 001, 4 → 0001.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
            ],
            options={
                'verbose_name': 'Configuración de Emprendimiento',
                'verbose_name_plural': 'Configuración de Emprendimiento',
                'db_table': 'ent_configuration',
            },
        ),
    ]
